# This rule is not used by the project local-ome itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over serving.local-ome.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: local-ome
    app.kubernetes.io/managed-by: kustomize
  name: localinferenceservice-admin-role
rules:
- apiGroups:
  - serving.local-ome.com
  resources:
  - localinferenceservices
  verbs:
  - '*'
- apiGroups:
  - serving.local-ome.com
  resources:
  - localinferenceservices/status
  verbs:
  - get
